/*
Copyright (C) 2022 Andrey Nazarov

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

[KEY_ESC] = K_ESCAPE,
[KEY_1] = '1',
[KEY_2] = '2',
[KEY_3] = '3',
[KEY_4] = '4',
[KEY_5] = '5',
[KEY_6] = '6',
[KEY_7] = '7',
[KEY_8] = '8',
[KEY_9] = '9',
[KEY_0] = '0',
[KEY_MINUS] = '-',
[KEY_EQUAL] = '=',
[KEY_BACKSPACE] = K_BACKSPACE,
[KEY_TAB] = K_TAB,
[KEY_Q] = 'q',
[KEY_W] = 'w',
[KEY_E] = 'e',
[KEY_R] = 'r',
[KEY_T] = 't',
[KEY_Y] = 'y',
[KEY_U] = 'u',
[KEY_I] = 'i',
[KEY_O] = 'o',
[KEY_P] = 'p',
[KEY_LEFTBRACE] = '[',
[KEY_RIGHTBRACE] = ']',
[KEY_ENTER] = K_ENTER,
[KEY_LEFTCTRL] = K_LCTRL,
[KEY_A] = 'a',
[KEY_S] = 's',
[KEY_D] = 'd',
[KEY_F] = 'f',
[KEY_G] = 'g',
[KEY_H] = 'h',
[KEY_J] = 'j',
[KEY_K] = 'k',
[KEY_L] = 'l',
[KEY_SEMICOLON] = ';',
[KEY_APOSTROPHE] = '\'',
[KEY_GRAVE] = '`',
[KEY_LEFTSHIFT] = K_LSHIFT,
[KEY_BACKSLASH] = '\\',
[KEY_Z] = 'z',
[KEY_X] = 'x',
[KEY_C] = 'c',
[KEY_V] = 'v',
[KEY_B] = 'b',
[KEY_N] = 'n',
[KEY_M] = 'm',
[KEY_COMMA] = ',',
[KEY_DOT] = '.',
[KEY_SLASH] = '/',
[KEY_RIGHTSHIFT] = K_RSHIFT,
[KEY_LEFTALT] = K_LALT,
[KEY_SPACE] = K_SPACE,
[KEY_CAPSLOCK] = K_CAPSLOCK,
[KEY_F1] = K_F1,
[KEY_F2] = K_F2,
[KEY_F3] = K_F3,
[KEY_F4] = K_F4,
[KEY_F5] = K_F5,
[KEY_F6] = K_F6,
[KEY_F7] = K_F7,
[KEY_F8] = K_F8,
[KEY_F9] = K_F9,
[KEY_F10] = K_F10,
[KEY_NUMLOCK] = K_NUMLOCK,
[KEY_SCROLLLOCK] = K_SCROLLOCK,
[KEY_KP7] = K_KP_HOME,
[KEY_KP8] = K_KP_UPARROW,
[KEY_KP9] = K_KP_PGUP,
[KEY_KPMINUS] = K_KP_MINUS,
[KEY_KP4] = K_KP_LEFTARROW,
[KEY_KP5] = K_KP_5,
[KEY_KP6] = K_KP_RIGHTARROW,
[KEY_KPPLUS] = K_KP_PLUS,
[KEY_KP1] = K_KP_END,
[KEY_KP2] = K_KP_DOWNARROW,
[KEY_KP3] = K_KP_PGDN,
[KEY_KP0] = K_KP_INS,
[KEY_KPDOT] = K_KP_DEL,
[KEY_102ND] = K_102ND,
[KEY_F11] = K_F11,
[KEY_F12] = K_F12,
[KEY_KPENTER] = K_KP_ENTER,
[KEY_RIGHTCTRL] = K_RCTRL,
[KEY_KPSLASH] = K_KP_SLASH,
[KEY_RIGHTALT] = K_RALT,
[KEY_HOME] = K_HOME,
[KEY_UP] = K_UPARROW,
[KEY_PAGEUP] = K_PGUP,
[KEY_LEFT] = K_LEFTARROW,
[KEY_RIGHT] = K_RIGHTARROW,
[KEY_END] = K_END,
[KEY_DOWN] = K_DOWNARROW,
[KEY_PAGEDOWN] = K_PGDN,
[KEY_INSERT] = K_INS,
[KEY_DELETE] = K_DEL,
[KEY_LEFTMETA] = K_LWINKEY,
[KEY_RIGHTMETA] = K_RWINKEY,
[KEY_COMPOSE] = K_MENU,
