/*
Copyright (C) 2025 Andrey Nazarov

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

{ "Escape", K_ESCAPE },
{ "Digit0", '0' },
{ "Digit1", '1' },
{ "Digit2", '2' },
{ "Digit3", '3' },
{ "Digit4", '4' },
{ "Digit5", '5' },
{ "Digit6", '6' },
{ "Digit7", '7' },
{ "Digit8", '8' },
{ "Digit9", '9' },
{ "Minus", '-' },
{ "Equal", '=' },
{ "Backspace", K_BACKSPACE },
{ "Tab", K_TAB },
{ "KeyA", 'a' },
{ "KeyB", 'b' },
{ "KeyC", 'c' },
{ "KeyD", 'd' },
{ "KeyE", 'e' },
{ "KeyF", 'f' },
{ "KeyG", 'g' },
{ "KeyH", 'h' },
{ "KeyI", 'i' },
{ "KeyJ", 'j' },
{ "KeyK", 'k' },
{ "KeyL", 'l' },
{ "KeyM", 'm' },
{ "KeyN", 'n' },
{ "KeyO", 'o' },
{ "KeyP", 'p' },
{ "KeyQ", 'q' },
{ "KeyR", 'r' },
{ "KeyS", 's' },
{ "KeyT", 't' },
{ "KeyU", 'u' },
{ "KeyV", 'v' },
{ "KeyW", 'w' },
{ "KeyX", 'x' },
{ "KeyY", 'y' },
{ "KeyZ", 'z' },
{ "BracketLeft", '[' },
{ "BracketRight", ']' },
{ "Enter", K_ENTER },
{ "ControlLeft", K_LCTRL },
{ "Semicolon", ';' },
{ "Quote", '\'' },
{ "Backquote", '`' },
{ "ShiftLeft", K_LSHIFT },
{ "Backslash", '\\' },
{ "Comma", ',' },
{ "Period", '.' },
{ "Slash", '/' },
{ "ShiftRight", K_RSHIFT },
{ "AltLeft", K_LALT },
{ "Space", K_SPACE },
{ "CapsLock", K_CAPSLOCK },
{ "F1", K_F1 },
{ "F2", K_F2 },
{ "F3", K_F3 },
{ "F4", K_F4 },
{ "F5", K_F5 },
{ "F6", K_F6 },
{ "F7", K_F7 },
{ "F8", K_F8 },
{ "F9", K_F9 },
{ "F10", K_F10 },
{ "F11", K_F11 },
{ "F12", K_F12 },
{ "Pause", K_PAUSE },
{ "ScrollLock", K_SCROLLOCK },
{ "Numpad0", K_KP_INS },
{ "Numpad1", K_KP_END },
{ "Numpad2", K_KP_DOWNARROW },
{ "Numpad3", K_KP_PGDN },
{ "Numpad4", K_KP_LEFTARROW },
{ "Numpad5", K_KP_5 },
{ "Numpad6", K_KP_RIGHTARROW },
{ "Numpad7", K_KP_HOME },
{ "Numpad8", K_KP_UPARROW },
{ "Numpad9", K_KP_PGUP },
{ "NumpadSubtract", K_KP_MINUS },
{ "NumpadAdd", K_KP_PLUS },
{ "NumpadDecimal", K_KP_DEL },
{ "NumpadEnter", K_KP_ENTER },
{ "NumpadDivide", K_KP_SLASH },
{ "NumpadMultiply", K_KP_MULTIPLY },
{ "PrintScreen", K_PRINTSCREEN },
{ "ControlRight", K_RCTRL },
{ "AltRight", K_RALT },
{ "NumLock", K_NUMLOCK },
{ "Home", K_HOME },
{ "ArrowUp", K_UPARROW },
{ "PageUp", K_PGUP },
{ "ArrowLeft", K_LEFTARROW },
{ "ArrowRight", K_RIGHTARROW },
{ "End", K_END },
{ "ArrowDown", K_DOWNARROW },
{ "PageDown", K_PGDN },
{ "Insert", K_INS },
{ "Delete", K_DEL },
{ "MetaLeft", K_LWINKEY },
{ "MetaRight", K_RWINKEY },
{ "ContextMenu", K_MENU },
